import builtins from "builtin-modules";
import esbuild from "esbuild";
import { copyFileSync, cpSync, mkdirSync, rmSync } from "node:fs";
import process from "node:process";

const watch = process.argv.includes("--watch");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source: https://github.com/kotborealis/slides-extended-mobile-preview
*/`;

const buildOptions = {
  banner: { js: banner },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external: ["obsidian", "electron", "codemirror", "@codemirror/language", "@codemirror/state", "@codemirror/view", "moment", ...builtins],
  format: "cjs",
  logLevel: "info",
  outfile: "main.js",
  platform: "node",
  sourcemap: "inline",
  target: "es2022",
};

function copyRevealAssets() {
  rmSync("assets/reveal", { force: true, recursive: true });
  mkdirSync("assets/reveal/theme", { recursive: true });
  mkdirSync("assets/reveal/plugin/notes", { recursive: true });

  copyFileSync("node_modules/reveal.js/dist/reveal.js", "assets/reveal/reveal.js");
  copyFileSync("node_modules/reveal.js/dist/reveal.css", "assets/reveal/reveal.css");
  cpSync("node_modules/reveal.js/dist/theme", "assets/reveal/theme", { recursive: true });
  copyFileSync("node_modules/reveal.js/dist/plugin/notes.js", "assets/reveal/plugin/notes/notes.js");
}

copyRevealAssets();

if (watch) {
  const ctx = await esbuild.context(buildOptions);
  await ctx.watch();
} else {
  await esbuild.build(buildOptions);
}
