import builtins from "builtin-modules";
import esbuild from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import process from "node:process";

const watch = process.argv.includes("--watch");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source: https://github.com/kotborealis/slides-extended-mobile-preview
*/`;

const revealCss = readFileSync("node_modules/reveal.js/dist/reveal.css", "utf-8");
const revealJs = readFileSync("node_modules/reveal.js/dist/reveal.js", "utf-8");
const notesJs = readFileSync("node_modules/reveal.js/dist/plugin/notes.js", "utf-8");

const themes = {};
const themeNames = ['black', 'white', 'league', 'beige', 'night', 'serif', 'simple', 'solarized', 'blood', 'moon', 'dracula', 'sky', 'black-contrast', 'white-contrast'];
for (const name of themeNames) {
  themes[name] = readFileSync(`node_modules/reveal.js/dist/theme/${name}.css`, "utf-8");
}

const themesJson = JSON.stringify(themes);

const buildOptions = {
  banner: { js: banner },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external: ["obsidian", "electron", "codemirror", "@codemirror/language", "@codemirror/state", "@codemirror/view", "moment", ...builtins],
  format: "cjs",
  logLevel: "info",
  outfile: "main.js",
  platform: "node",
  sourcemap: "inline",
  target: "es2022",
  define: {
    "REVEAL_CSS": JSON.stringify(revealCss),
    "REVEAL_JS": JSON.stringify(revealJs),
    "NOTES_JS": JSON.stringify(notesJs),
    "THEMES": themesJson,
  },
};

if (watch) {
  const ctx = await esbuild.context(buildOptions);
  await ctx.watch();
} else {
  await esbuild.build(buildOptions);
}